---

#############################################################################
##
##  Auto-Ozmeka
##  T McIntyre for UTS EResearch 2015
##
#############################################################################


- hosts: all
  user: vagrant
  become: yes
  roles:
    - omeka-s